queue:
  engineRequestQueue: ${TRANSFORM_ENGINE_REQUEST_QUEUE:org.alfresco.transform.engine.imagemagick.acs}
transform:
  core:
    imagemagick:
      root: ${IMAGEMAGICK_ROOT:/usr/lib64/ImageMagick-7.1.2}
      dyn: ${IMAGEMAGICK_DYN:/usr/lib64/ImageMagick-7.1.2/lib}
      exe: ${IMAGEMAGICK_EXE:/usr/bin/convert}
      coders: ${IMAGEMAGICK_CODERS:}
      config: ${IMAGEMAGICK_CONFIG:}
      commandOptions:
        enabled: ${IMAGEMAGICK_COMMAND_OPTIONS_ENABLED:false}
