queue:
  engineRequestQueue: ${TRANSFORM_ENGINE_REQUEST_QUEUE:org.alfresco.transform.engine.imagemagick.acs}
transform:
  core:
    imagemagick:
      backend: ${IMAGEMAGICK_BACKEND:imagemagick}
      root: ${IMAGEMAGICK_ROOT:}
      dyn: ${IMAGEMAGICK_DYN:}
      exe: ${IMAGEMAGICK_EXE:}
      coders: ${IMAGEMAGICK_CODERS:}
      config: ${IMAGEMAGICK_CONFIG:}
      threads: ${IMAGEMAGICK_THREADS:}
      commandOptions:
        enabled: ${IMAGEMAGICK_COMMAND_OPTIONS_ENABLED:false}
