repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-json
      - id: check-xml
      - id: check-merge-conflict
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: end-of-file-fixer
        exclude: \.(pgm|pnm|ppm)$
      - id: trailing-whitespace
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.13.0
    hooks:
      - id: check-travis
      - id: check-github-workflows
