repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
        exclude: application-default.yaml
      - id: check-json
      - id: check-xml
      - id: check-merge-conflict
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: ['--fix=lf']
        exclude: (templates|test/resources)/.*$
      - id: end-of-file-fixer
        exclude: (templates|test/resources)/.*$
      - id: trailing-whitespace
        exclude: (templates|test/resources)/.*$
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.13.0
    hooks:
      - id: check-travis
      - id: check-github-workflows
      - id: check-jsonschema
        alias: check-dependabot
        name: "Validate Dependabot Config"
        files: '.github/dependabot\.yml$'
        args: ["--schemafile", "https://json.schemastore.org/dependabot-2.0.json"]
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.4.0
    hooks:
      - id: editorconfig-checker
        args: ['-disable-indent-size']
        exclude: (templates|test/resources)/.*$
