repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
        exclude: application-default.yaml
      - id: check-json
      - id: check-xml
      - id: check-merge-conflict
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: end-of-file-fixer
        exclude: \.(pgm|pnm|ppm)$
      - id: trailing-whitespace
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.13.0
    hooks:
      - id: check-travis
      - id: check-github-workflows
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.4.0
    hooks:
      - id: editorconfig-checker
        args: ['-disable-indent-size']
        exclude: (\.(pgm|pnm|ppm|html|eml)|quick.txt)$
