---
language: java
jdk: openjdk17
os: linux
dist: focal

git:
  depth: false
  quiet: true

services:
  - docker

cache:
  directories:
    - ${HOME}/.m2/repository
    - ${HOME}/artifacts

branches:
  only:
    - master
    - /^SP\/.+$/
    - /^HF\/.+$/
    - /^ATS-.*$/
    - /^ACS-.*$/

stages:
  - name: Veracode Scan
    if: branch = master
  - build and test
  - release

before_install: bash _ci/init.sh

jobs:
  include:
    - stage: Veracode Scan
      name: "Veracode - Source Clear Scan (SCA)" 
      install: skip
      script: travis_wait 30 bash _ci/source_clear.sh

    - stage: Build and Test
      name: "Core & Base Snapshot deployment" # This is to separate the snapshot deployment from the following jobs, to prevent duplication on nexus
      if: branch = master AND type != pull_request
      before_script: travis_wait bash _ci/cache_artifacts.sh
      install: travis_wait 20 mvn -B -U -q clean install -DadditionalOption=-Xdoclint:none -DskipTests -Dmaven.javadoc.skip=true -Dmaven.wagon.http.pool=false -Pbase
      script: mvn -B -U clean deploy -DadditionalOption=-Xdoclint:none -Dmaven.javadoc.skip=true -Dmaven.wagon.http.pool=false -Pbase

    - name: "ImageMagick"
      before_script: travis_wait bash _ci/cache_artifacts.sh
      install: _ci/build.sh imagemagick
      script: bash _ci/test.sh imagemagick

    - name: "LibreOffice"
      before_script: travis_wait bash _ci/cache_artifacts.sh
      install: _ci/build.sh libreoffice
      script: bash _ci/test.sh libreoffice

    - name: "Transform Misc"
      before_script: travis_wait bash _ci/cache_artifacts.sh
      install: _ci/build.sh misc
      script: bash _ci/test.sh misc

    - name: "PDF Renderer"
      before_script: travis_wait bash _ci/cache_artifacts.sh
      install: _ci/build.sh pdf-renderer
      script: bash _ci/test.sh pdf-renderer

    - name: "Tika"
      before_script: travis_wait bash _ci/cache_artifacts.sh
      install: _ci/build.sh tika
      script: bash _ci/test.sh tika

    - name: "All in One Transformer"
      before_script: travis_wait bash _ci/cache_artifacts.sh
      install: _ci/build.sh full-build
      script:  travis_wait 30 bash _ci/test.sh aio-test

    - name: "Release"
      stage: release
      if: commit_message ~= /\[release\]/ AND branch ~= /^(master|ATS-0000_refactor_packages|SP\/.+|HF\/.+)$/
      before_script: travis_wait bash _ci/cache_artifacts.sh
      script: travis_wait 55 bash _ci/release.sh
