queue:
  engineRequestQueue: ${TRANSFORM_ENGINE_REQUEST_QUEUE:org.alfresco.transform.engine.misc.acs}
transform:
  core:
    misc:
      pdfBox:
        defaultFont: ${MISC_PDFBOX_DEFAULT_FONT:NotoSans-Regular}
      htmlOptions:
        collapseHtml: ${MISC_HTML_COLLAPSE:true}
