queue:
  engineRequestQueue: ${TRANSFORM_ENGINE_REQUEST_QUEUE:org.alfresco.transform.engine.ffmpeg.acs}
transform:
  core:
    version: @project.version@
    config:
      location: classpath:ffmpeg_engine_config.json
    ffmpeg:
      exe: ${FFMPEG_EXE:/usr/bin/ffmpeg}