---
spring:
  servlet:
    multipart:
      max-file-size: 8192MB
      max-request-size: 8192MB
  activemq:
    broker-url: ${ACTIVEMQ_URL:nio://localhost:61616}?jms.watchTopicAdvisories=false
    user: ${ACTIVEMQ_USER:admin}
    password: ${ACTIVEMQ_PASSWORD:admin}
    pool:
      enabled: true
      max-connections: 20
  jackson:
    default-property-inclusion: non_empty

server:
  port: 8090

logging:
  level:
    # org.alfresco.util.exec.RuntimeExec: debug
    org.alfresco.transformer.LibreOfficeController: debug
    org.alfresco.transformer.JodConverterSharedInstance: debug
    org.alfresco.transformer.AlfrescoPdfRendererController: debug
    org.alfresco.transformer.ImageMagickController: debug
    org.alfresco.transformer.TikaController: debug
    org.alfresco.transformer.MiscellaneousTransformersController: debug

fileStoreUrl: ${FILE_STORE_URL:http://localhost:8099/alfresco/api/-default-/private/sfs/versions/1/file}

jms-listener:
  concurrency: ${JMS_LISTENER_CONCURRENCY:1-10}

management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - prometheus
          - health
  metrics:
    enable[http]: false
    enable[logback]: false
    enable[tomcat]: false
    enable[jvm.classes]: false

container:
  name: ${HOSTNAME:t-engine}

transform:
    imagemagick:
      root: ${IMAGEMAGICK_ROOT:/usr/lib64/ImageMagick-7.0.7}
      dyn: ${IMAGEMAGICK_DYN:/usr/lib64/ImageMagick-7.0.7/lib}
      exe: ${IMAGEMAGICK_EXE:/usr/bin/convert}
    pdf_renderer: ${PDF_RENDERER_EXE:/usr/bin/alfresco-pdf-renderer}
    libreoffice: ${LIBREOFFICE_HOME:/opt/libreoffice6.1}

