queue:
  engineRequestQueue: ${TRANSFORM_ENGINE_REQUEST_QUEUE:org.alfresco.transform.engine.libreoffice.acs}
transform:
  core:
    config:
      location: classpath:libreoffice_engine_config.json
    libreoffice:
      path: ${LIBREOFFICE_HOME:/opt/libreoffice6.3}
      timeout: ${LIBREOFFICE_TIMEOUT:1200000}