queue:
  engineRequestQueue: ${TRANSFORM_ENGINE_REQUEST_QUEUE:org.alfresco.transform.engine.libreoffice.acs}
transform:
  core:
    config:
      location: classpath:libreoffice_engine_config.json
    libreoffice:
      path: ${LIBREOFFICE_HOME:/opt/libreoffice6.3}
      maxTasksPerProcess: ${LIBREOFFICE_MAX_TASKS_PER_PROCESS:200}
      timeout: ${LIBREOFFICE_TIMEOUT:1200000}
      portNumbers: ${LIBREOFFICE_PORT_NUMBERS:8100}
      templateProfileDir: ${LIBREOFFICE_TEMPLATE_PROFILE_DIR:}
      isEnabled: ${LIBREOFFICE_IS_ENABLED:true}