queue:
  engineRequestQueue: ${TRANSFORM_ENGINE_REQUEST_QUEUE:org.alfresco.transform.engine.libreoffice.acs}
transform:
  config:
    location: classpath:libreoffice_engine_config.json
libreoffice:
  executor:
    path: ${LIBREOFFICE_HOME:/opt/libreoffice6.1}