queue:
  engineRequestQueue: ${TRANSFORM_ENGINE_REQUEST_QUEUE:org.alfresco.transform.engine.tika.acs}
transform:
  core:
    config:
      location: classpath:tika_engine_config.json
    tika:
      pdfBox:
        notExtractBookmarksTextDefault: ${PDFBOX_NOTEXTRACTBOOKMARKS_DEFAULT:false}

logging:
  level:
    # org.alfresco.util.exec.RuntimeExec: debug
    org.alfresco.transformer.metadataExtractors.TikaAudioMetadataExtractor: debug
    org.alfresco.transformer.metadataExtractors: debug
