queue:
  engineRequestQueue: ${TRANSFORM_ENGINE_REQUEST_QUEUE:org.alfresco.transform.engine.tika.acs}
transform:
  core:
    version: @project.version@
    config:
      location: classpath:tika_engine_config.json
    tika:
      pdfBox:
        notExtractBookmarksTextDefault: ${PDFBOX_NOTEXTRACTBOOKMARKS_DEFAULT:false}
      exifTool:
        windowsOS: exiftool -args -G1 -sep \"|||\" \#{'$'}{INPUT}
        unixOS: env FOO=\#{'$'}{OUTPUT} exiftool -args -G1 -sep "|||" \#{'$'}{INPUT}